### ISSUE TITLE
[1.21] Enchantment issues

### ISSUE THREAD

**Issue by kwpugh** [BarchamMal/MC-Extended#14]
I guess there is a problem with some of the `enchantable` tags

armors aren't enchantable
![Screenshot 2024-07-25 at 9 17 35 PM](https://github.com/user-attachments/assets/4e80e1eb-73d8-441e-9581-19650defef1a)

the tools and weapons can't be enchanted either
![Screenshot 2024-07-25 at 9 17 44 PM](https://github.com/user-attachments/assets/6ae4bf74-7d9c-4241-b308-99e0b7774609)

**Comment by BarchamMal** [comment]
I will look into this.

**Comment by kwpugh** [comment]
Minecraft looks for items in `Minecraft/tags/item/enchantable` for standard tags containing items that can be enchanted in the table

![Screenshot 2024-07-26 at 8 43 26 AM](https://github.com/user-attachments/assets/aab45103-415f-4d83-bfa3-52b4966b2e77)

**Comment by BarchamMal** [comment]
This is due to the update as well... I guess cause of the data-driven enchantments. will be resolved soon.

**Comment by BarchamMal** [comment]
it would seem that tools and weapons **can** be enchanted.
