### ISSUE TITLE
[1.21] Mature crops do not drop crops

### ISSUE THREAD

**Issue by kwpugh** [BarchamMal/MC-Extended#15]
Breaking mature tomato, onion, and spinach plants does not drop crops.

**Comment by BarchamMal** [comment]
This must be a 1.21 specific bug which started with the update... that's why it's still in beta I guess... I will look into this.

**Comment by BarchamMal** [comment]
https://github.com/BarchamMal/MC-Extended/commit/2dac6fca69942fb73ade06003ebf96ea410b1ec5 also fixed this

**Comment by BarchamMal** [comment]
https://github.com/BarchamMal/MC-Extended/commit/2dac6fca69942fb73ade06003ebf96ea410b1ec5 also fixed this
