### ISSUE TITLE
[1.21] Ores are not breakable

### ISSUE THREAD

**Issue by kwpugh** [BarchamMal/MC-Extended#16]
Tried vanilla iron, diamond, and netherite pickaxes

Also tried your ruby, sapphire, and bronze pickaxes.

**Comment by BarchamMal** [comment]
Darn! must also be due to the update... looking into...

**Comment by kwpugh** [comment]
You are using the outdated `FabricBlockSettings` approach to block register.  We just use vanilla now.

Here is an example of the 1.21

`	public static final Block CITRINE_ORE = new BaseOreBlock(UniformIntProvider.create(0, 2), 
			AbstractBlock.Settings.copy(Blocks.STONE).requiresTool().strength(2.0F, 2.0F));`

**Comment by kwpugh** [comment]
in the above example, I use a custom `BaseOreBlock` that just extends `ExperienceDroppingBlock`.

**Comment by BarchamMal** [comment]
Theory confirmed, this is due to the update... working on it.

**Comment by kwpugh** [comment]
Also, keep in mind mojang changed the loot table json structure slightly with 1.21, it any blocks you have with drops are likely affected.

**Comment by BarchamMal** [comment]
huh! it auto-closed it... I think I fixed it in [this commit](https://github.com/BarchamMal/MC-Extended/commit/2dac6fca69942fb73ade06003ebf96ea410b1ec5)

**Comment by BarchamMal** [comment]
> Also, keep in mind mojang changed the loot table json structure slightly with 1.21, it any blocks you have with drops are likely affected.

heh heh. I noticed.
