### ISSUE TITLE
[1.21] Tools and weapons don't show default modifiers

### ISSUE THREAD

**Issue by kwpugh** [BarchamMal/MC-Extended#17]
Normally weapons and tools show modifiers
![Screenshot 2024-07-26 at 8 37 04 AM](https://github.com/user-attachments/assets/aa9f669d-4018-419b-b0e4-806181ef93c1)

Yours do not
![Screenshot 2024-07-26 at 8 36 40 AM](https://github.com/user-attachments/assets/d6ef756a-2255-4a0f-971b-3c9d94eef4b2)

**Comment by BarchamMal** [comment]
Huh! with this many bugs... I should have made it `ALPHA` I'll try to find what on earth causes this!

**Comment by kwpugh** [comment]
They changed the way tools and weapons are registered.

I tweaked yours to look like this
![Screenshot 2024-07-26 at 11 58 07 AM](https://github.com/user-attachments/assets/a61cd01d-fe81-40ad-b50f-55240edcd1bd)

I added baseAttackDamage of 3 since your sword was only giving attack damage of 4 on ruby sword.

example code:
`    public static final Item RUBY_SWORD = new SwordItem(INSTANCE,
            (new Item.Settings()).attributeModifiers(SwordItem.createAttributeModifiers(INSTANCE, 3, -2.4F)));`

**Comment by kwpugh** [comment]
Attack damage of 7 comes from:

1 (builtin my Minecraft) + 3 (from the material) + 3 (baseAttackDamage at register) = 7

**Comment by BarchamMal** [comment]
Thanks for this solution and all your help. Also, if you would like to speed things up, you could fork the rep and make a PR.

**Comment by kwpugh** [comment]
Some other thoughts.

it is not recommended to instantiate utility class
` public static final ArFoMiToVi AR_FO_MI_TO_VI = new ArFoMiToVi();`

or to register items from an instance object
`AR_FO_MI_TO_VI.RegisterAll();`

you can call you register methods directly from `onInitialize()` 
`Minerals.RegisterAll();
        Foods.RegisterAll();
        Misc.RegisterAll();
        ArmorMaterials.RegisterAll();
        ToolMaterials.RegisterAll();
        Villagers.RegisterAll();
        Entities.RegisterAll();`

Lastly, it is not a good idea to name classes the same as vanilla, such as `ArmorMaterials` and `ToolMaterials`

Keep up the hard work.

**Comment by kwpugh** [comment]
oh, one more thing.

Don't do this:
`public static final String NAMESPACE = "mc-extended";`

do this:
`public static final String MC_EXTENDED = "mc-extended";`

your mod id gets used throughout the game and messages get put into logs with the id.  It should be unique to your mod, not generic.

**Comment by BarchamMal** [comment]
Yeah, if you did a thing or two (A PR or so) you'd be in the contributors...

**Comment by BarchamMal** [comment]
Per your suggestions I'll change those... I thought I had a long time ago.

**Comment by kwpugh** [comment]
I'll let you manage your own code, I have 32 mods of my own to manage.
