### ISSUE TITLE
[1.21] Armor layers are bugged

### ISSUE THREAD

**Issue by BarchamMal** [BarchamMal/MC-Extended#18]
![image](https://github.com/user-attachments/assets/6865fefa-4685-4990-a64c-f9e8ff171c10)
And this goes for all of my mod's armor.

**Comment by kwpugh** [comment]
You can use one of my mods if you need some examples
[emerald_tools_fabric-1.21.zip](https://github.com/user-attachments/files/16394081/emerald_tools_fabric-1.21.zip)

**Comment by kwpugh** [comment]
You can fix the armor by removing the `NAMESPACE` for the register code.

you have:  `List<ArmorMaterial.Layer> layers = List.of(new ArmorMaterial.Layer(Identifier.of(NAMESPACE, id), "", dyeable));`

change to:  ` List<ArmorMaterial.Layer> list = List.of(new ArmorMaterial.Layer(Identifier.of(id)));`

It needs to find the layers in the `minecraft` namespace, you are telling it to look in your mod's namespace.

**Comment by kwpugh** [comment]
![Screenshot 2024-07-26 at 11 29 29 AM](https://github.com/user-attachments/assets/033c659e-5099-4037-ac50-707a49e319a0)

**Comment by BarchamMal** [comment]
I see, I should have used ofVanilla...

**Comment by kwpugh** [comment]
in your case `id` will default to `minecraft` namespace

**Comment by BarchamMal** [comment]
I'll implement this rights away.

**Comment by kwpugh** [comment]
If you have more questions as you go along or want to chit-chat about modding, I have a mod-dev channel on my discord: https://discord.gg/j7bYbkW

Feel free to drop by.
